version: '3'
services:
  db:
    image: mysql@sha256:dce31fcdd15aaedb5591aa89f19ec37cb79981af46511781fa41287d88ed0abd
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    command: /bin/sh #bundle exec rails server -p 3000 -b '0.0.0.0'
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:3000:3000"
